### ISSUE TITLE
api, or adding decks

### ISSUE THREAD

**Issue by xeor** [ankicommunity/anki-sync-server#76] opened 2021-03-07 22:57 UTC
Would it be a good idea to add an api or a cli for adding decks to this server? It would solve a huge problem for many people that don't want to use ankiconnect.

There are currently (at least that I could find), no way of adding decks without the anki ui. Being ankiweb or this server.

Goal is to automatically scan a bunch of markdown files and add from them, but without any ui.

Or is an api/cli for adding decks in this server impossible for some reasons? Technical or legally?

**Comment by VikashKothary** [comment] 2021-03-08 16:01
Hi @xeor,

This project originally did have a full API but in its current state it only supports syncing.

Our newer project, djankiserv (https://github.com/ankicommunity/djankiserv) will support a complete API. So maybe that is something you'd be interested in.

In fact, developing a stable and powerful API is a goal of this community so your feedback on that project would be much appreciated. Hopefully it should be able to help you in your use case.

**Comment by VikashKothary** [comment] 2021-06-02 21:11
I hope the answer above resolved your issue. I'm going to close this issue but feel free to open any issues regarding an API on the djankiserv repo.

**Closed by VikashKothary** 2021-06-02 21:11 UTC

**Comment by rounakdatta** [comment] 2022-05-18 14:47
@VikashKothary the djankiserv seems to be a stalled project, are we planning to build the Anki API soon?

**Comment by VikashKothary** [comment] 2022-05-18 17:08
Officially, it's not stalled. I'm just planning some architectural changes to reduce the complexity and improve it's compatibility with other services like this one. 

But until then feedback/contributions are always welcome. Have you used Djankiserv? How are you finding it? 

The problem is that anki-sync-server has been around for a while so we get a lot more contributions and therefore it takes up more of my time. But I hope to also get some more maintainers on to assist with the task.

I'm really excited with the future of Djankiserv. I think it'll provide a lot of value to our community.

**Comment by LuckyTurtleDev** [comment] 2022-10-03 18:50
Exist a documentation about the syncing api? If syncing is possible with the current api, adding/editing of cards should be also possible with the same api.

As example I would like to edit existing cards.
I regular add new cards at my mobile phone, if I see a unknown English world somewhere. Later I add a audio file at pc to this card to also learn the spelling.
I would like to automate the second step, by searching the word at leo.org, downloading the audio file and adding it to the card.

**Comment by VikashKothary** [comment] 2022-10-13 19:23
I believe there is documentation regarding the sync api but I don't remember where I saw it I'm afraid. The Sync API is very custom to Anki and frankly isn't very pleasant to work with. You can see the endpoints here: 

https://github.com/ankicommunity/anki-sync-server/blob/734d9e6b290a1f15aea9432535531c7e0568f92d/src/ankisyncd/sync_app.py#L46

(Personally, I think the Django code is easier to understand which you can find here: https://github.com/ankicommunity/anki-api-server/blob/develop/src/djankiserv_sync/urls.py.)

You could possibly use these endpoints but for a better developer experience, I'm trying to improve the anki-api-server (a rebrand for djankiserv) such that it provides an restful API as you might expect.

@LuckyTurtleDev  The use case your looking into is exactly the type I'd like to support with the anki-api-server. I would suggest you checking it out to see if it meets your needs.

**Comment by LuckyTurtleDev** [comment] 2022-10-13 20:08
I have found an anki addon that does provide a api.
https://foosoft.net/projects/anki-connect/
But it does requeired a running anki client.

I think would be a nice idea to create a api witch is compatible with the anki conntech api. This would allow to also use existing programms.
New programs can target the sync server and the anki client at the same time.

**Comment by VikashKothary** [comment] 2022-10-14 17:40
I'm familiar with Anki Connect. I think it's a fantastic project. We even have a fork here in the community if case you want to contribute to it.

It's important to note that Anki Connect had some constraints to its design due to the fact that it had to run in AnkiDesktop. Our Anki API Server would not have to follow those constrains as such we should be able to create a more developer-friendly API which follows industry standards when designing REST APIs. 

That being said, I think it's an interesting idea. There may be value in the future to support the Anki Connect data format. It would allow developers to migrate their existing integrations over to the Anki API Server, while benefiting from other features of the project. 

It's something I'll keep in mind but I don't know if we're there yet. I'm still in the process of making the existing endpoints more RESTful and hopefully improving the database design. I would suggest creating a ticket here if you'd like to see that feature in the future: https://github.com/ankicommunity/anki-api-server/issues/new
