### ISSUE TITLE
Incompatible with arch-based clients

### ISSUE THREAD

**Issue by AlexBocken** [ankicommunity/anki-sync-server#24] opened 2020-09-05 09:25 UTC
Hi there!

I've noticed how the syncing does not appear to work with arch based clients. Here's the log of me trying to sync this way:

```
◆ src ❯❯❯ python -m ankisyncd
[2020-09-05 11:12:31,367]:INFO:ankisyncd:ankisyncd 049bb04 (https://github.com/tsudoko/anki-sync-server)
[2020-09-05 11:12:31,378]:INFO:ankisyncd:Loaded config from /root/anki-sync-server/src/ankisyncd.conf
[2020-09-05 11:12:31,379]:INFO:ankisyncd.users:Found auth_db_path in config, using SqliteUserManager for auth
[2020-09-05 11:12:31,380]:INFO:ankisyncd.sessions:Found session_db_path in config, using SqliteSessionManager for auth
[2020-09-05 11:12:31,382]:INFO:ankisyncd:Serving HTTP on 0.0.0.0 port 27702...
[2020-09-05 11:12:36,191]:INFO:ankisyncd.CollectionThread[alex]:Starting...
[2020-09-05 11:12:36,191]:INFO:ankisyncd.CollectionThread[alex]:Running meta(*[], **{'v': 10, 'cv': 'ankidesktop,2.1.26 (arch-linux-2.1.26-1),lin:arch:'})
[2020-09-05 11:12:36,202]:ERROR:ankisyncd.CollectionThread[alex]:Unable to meta(*[], **{'v': 10, 'cv': 'ankidesktop,2.1.26 (arch-linux-2.1.26-1),lin:arch:'}): invalid literal for int() with base 10:
'h-linux-2.1.26-1)'
Traceback (most recent call last):
  File "/root/anki-sync-server/src/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/root/anki-sync-server/src/ankisyncd/collection.py", line 45, in execute
    ret = func(*args, **kw)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 575, in run_func
    res = handler_method(**keyword_args)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 89, in meta
    if self._old_client(cv):
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 71, in _old_client
    note[name] = int(vs[-1])
ValueError: invalid literal for int() with base 10: 'h-linux-2.1.26-1)'
Traceback (most recent call last):
  File "/usr/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python3.8/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/usr/lib/python3.8/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 519, in __call__
    result = self._execute_handler_method_in_thread(url, data, session)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 584, in _execute_handler_method_in_thread
    result = thread.execute(run_func, kw=keyword_args)
  File "/root/anki-sync-server/src/ankisyncd/thread.py", line 79, in execute
    raise ret
  File "/root/anki-sync-server/src/ankisyncd/thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "/root/anki-sync-server/src/ankisyncd/collection.py", line 45, in execute
    ret = func(*args, **kw)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 575, in run_func
    res = handler_method(**keyword_args)
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 89, in meta
    if self._old_client(cv):
  File "/root/anki-sync-server/src/ankisyncd/sync_app.py", line 71, in _old_client
    note[name] = int(vs[-1])
ValueError: invalid literal for int() with base 10: 'h-linux-2.1.26-1)'
[2020-09-05 11:12:36,208]:INFO:ankisyncd.http:127.0.0.1 "POST /sync/meta HTTP/1.0" 500 59
^C[2020-09-05 11:12:41,917]:INFO:ankisyncd:Exiting...
```

Looking into the mentioned file it seems because in the code it just checks whether the name includes "alpha", "beta" or "rc". A**rc**h based clients do seem get wrongly included in that check:

`anki-sync-server/src/ankisyncd/sync_app.py`:
```python
note = {"alpha": 0, "beta": 0, "rc": 0}
        client, version, platform = cv.split(',')

        for name in note.keys():
            if name in version:
                #if name in 'arch':
                #    break
                vs = version.split(name)
                version = vs[0]
                note[name] = int(vs[-1])
```

Commented out in that section you can see my "fix" which makes the program at least usable to me. Could maybe someone with better coding skills than me look into implementing an actual fix?

**Comment by VikashKothary** [comment] 2020-09-05 09:51
Thank you for raising this issue. It's a nice catch.

Seems simple enough to solve. I see three steps: 
- [ ] reproducte the code;
- [ ] add a test case to catch this kind of issue;
- [ ] fix the code.

I'll try and find some time this weekend to have a patch for this issue.

**Comment by samyak-jain** [comment] 2020-11-15 23:00
Hey. @VikashKothary, were you able to take a look at the issue?
My cv variable looks like `ankidesktop,2.1.26 (arch-linux-2.1.26-1),lin:arch:`
Can you share what it looks like on a non arch based system? I can try taking a crack at this issue but I'm not sure what the code is trying to do here.

**Comment by VikashKothary** [comment] 2020-12-05 18:43
Hi @samyak-jain, apologies for the delay. 

I'm happy with your fix so far but I can see this becoming an issue for others again due to the actually implementation check. So if it's okay with you, can you also add a test for this as part of your PR.

You can see a list of different CV variables here: https://github.com/ankicommunity/anki-sync-server/blob/a55d1a35ee31ecea35431766b10aa457f8bf3f8f/tests/test_sync_app.py#L29. Can I ask you to add your CV to that list as confirm the test case confirms your fix?

**Comment by samyak-jain** [comment] 2020-12-17 01:18
Hey @VikashKothary, I've added the test case to my PR. I couldn't find any instructions on how to run the unit tests. 
My attempt at running the tests resulted in:
```
ModuleNotFoundError: No module named 'ankisyncd'
ModuleNotFoundError: No module named 'webtest'
```

**Comment by VikashKothary** [comment] 2020-12-23 23:34
Apologies about that. I've run the tests and they pass so I've merged your PR.

I've also fixed the unittests so you should be able to run the easily with a `make tests`. You can see the fix in this PR. https://github.com/ankicommunity/anki-sync-server/pull/62. Why doesn't you review my PR so see if that solves your problem. If you're happy leave a comment then I'll merge the PR.

**Closed** 2020-12-23 23:37 UTC
